#!/usr/bin/env bash
set -euo pipefail

rm -rf build-container

cmake -S . -B build-container -G Ninja \
  -DMULTI_PLANE_RUNTIME_MANAGER_ENABLE_DYNAMIC_PLUGINS=ON \
  -DMULTI_PLANE_RUNTIME_MANAGER_ENABLE_METADATA_FIELDS=ON \
  -DMULTI_PLANE_RUNTIME_MANAGER_ENABLE_ACL=OFF \
  -DMULTI_PLANE_RUNTIME_MANAGER_BUILD_REQUIREMENTS_TESTS=ON \
  -DMULTI_PLANE_RUNTIME_MANAGER_BUILD_PLUGIN_INTEGRATION_TESTS=ON \
  -DMULTI_PLANE_RUNTIME_MANAGER_BUILD_METADATA_UNIT_TESTS=ON \
  -DMULTI_PLANE_RUNTIME_MANAGER_BUILD_METADATA_VECTOR_TESTS=ON \
  -DMULTI_PLANE_RUNTIME_MANAGER_BUILD_METADATA_MSGPACK_VECTOR_TESTS=ON \
  -DMULTI_PLANE_RUNTIME_MANAGER_BUILD_DYNAMIC_PLUGIN_UNIT_TESTS=ON \
  -DMULTI_PLANE_RUNTIME_MANAGER_BUILD_DYNAMIC_PLUGIN_LIVE_TESTS=ON \
  -DMULTI_PLANE_RUNTIME_MANAGER_BUILD_FEATURE_MATRIX_SPEC_TESTS=ON

cmake --build build-container -j"$(nproc)"
ctest --test-dir build-container --output-on-failure
